### ISSUE TITLE
Problem with gulp

### ISSUE THREAD

**Issue by Arystosedes** [animalus/shared-lib-example#1]
1. Clone repo
2. npm i
3. install gulp if you don't have it (npm i gulp -g)
4. gulp dev

Error:
```
[09:23:45] 'sandbox' errored after 269 ms
[09:23:45] Error: spawn ng ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

5. gulp dev:android
```
[09:24:23] Starting '<anonymous>'...
{
  'Wi-Fi': {
    address: 'xxx.xxx.xxx.xxx',
    netmask: '255.255.255.0',
    family: 'IPv4',
    mac: 'xx:xx:xx:xx:xx:xx',
    internal: false,
    cidr: 'xx.xx.xx.xx/xx'
  }
}
[09:24:24] '<anonymous>' errored after 1.08 s
[09:24:24] Error: Can't determine local IP address.
    at C:\temp\shared-lib-example\node_modules\@animalus\gulp-dev-tools\gulp-utils.js:182:27
    at bound (domain.js:426:14)
    at runBound (domain.js:439:12)
    at asyncRunner (C:\temp\shared-lib-example\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[09:24:25] 'dev:android' errored after 1.65 s
```

**Comment by crowmagnumb** [comment]
Ah, sorry. Yeah, these all had to do with the @animalus/gulp-dev-tools of which I am also the author. This was my set of internal build tools that I needed to use here for consistency so I published them but they had a few assumptions about setup. The first problem you ran into had to do with the assumption that the angular-cli is globally installed. I fixed gulp-dev-tools to first check the `node_modules/.bin` directory for the executable before assuming globally installed. That will fix your problem here because the angular-cli is installed in this repo. The second problem you experienced is an attempt to look up your local IP address for which I was throwing an error, but instead I now just return the string "localhost". But that actually doesn't matter here since there are no api calls in this repo so instead of throwing an error it will just now print a "warning" that you can ignore.

As you correctly figured out this requires gulp globally, but it also assumes you have `tns` installed globally. If not, you can add it to the `package.json` and then the new check on local installs will take it from there. So basically, if you just do

```
git pull
npm i
```
... and try again.

**Comment by crowmagnumb** [comment]
Haven't heard back. closing.
